CREATE TABLE `s_users` (
  `id` bigint NOT NULL COMMENT '系统用户唯一ID',
  `old_user_id` int DEFAULT NULL COMMENT '旧表用户id',
  `old_order_id` bigint DEFAULT NULL COMMENT '老订单id',
  `account` varchar(50) DEFAULT NULL COMMENT '用户系统账号',
  `pwd` varchar(200) DEFAULT NULL COMMENT '系统密码',
  `surname` varchar(100) DEFAULT NULL COMMENT '姓氏',
  `chinese_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '中文名称',
  `nickname` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '用户昵称',
  `email` varchar(50) DEFAULT NULL COMMENT '用户邮箱',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `last_date` datetime DEFAULT NULL COMMENT '最后登录时间',
  `sex` varchar(2) DEFAULT NULL COMMENT '性别1：男2：女',
  `birthday` datetime DEFAULT NULL COMMENT '出生年月',
  `nationality` varchar(50) DEFAULT NULL COMMENT '国籍',
  `province` varchar(100) DEFAULT NULL COMMENT '省份(籍贯)',
  `cities` varchar(50) DEFAULT NULL COMMENT '城市(籍贯)',
  `address` varchar(255) DEFAULT NULL COMMENT '户籍地址',
  `address_province` varchar(36) DEFAULT NULL COMMENT '现在住址(省)',
  `address_city` varchar(45) DEFAULT NULL COMMENT '现住址(市)',
  `address_area` varchar(45) DEFAULT NULL COMMENT '现住址(区)',
  `address_street` varchar(45) DEFAULT NULL COMMENT '现住址(街道)',
  `id_type` int DEFAULT NULL COMMENT '证件类型',
  `id_number` varchar(36) DEFAULT NULL COMMENT '证件号',
  `car_no` varchar(30) DEFAULT NULL COMMENT '车牌号',
  `education` varchar(36) DEFAULT NULL COMMENT '学历',
  `age` int DEFAULT NULL COMMENT '年龄',
  `household_province` varchar(24) DEFAULT NULL COMMENT '户籍所在地省',
  `household_city` varchar(24) DEFAULT NULL COMMENT '户籍所在地城市',
  `blood` varchar(24) DEFAULT NULL COMMENT '血型',
  `career` varchar(24) DEFAULT NULL COMMENT '职业',
  `register_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `status` int NOT NULL DEFAULT '1' COMMENT '激活状态 激活为1，注销为2',
  `finish_status` tinyint NOT NULL DEFAULT '1' COMMENT '用户完成状态（1. 完成注册 2. 完成档案 3. 完成测评 4. 完成训练计划创建）',
  `login_type` varchar(255) DEFAULT NULL COMMENT '登陆类型 jumper-doctor 医生端，jumper-angelApp孕妇端',
  `grade_name` smallint DEFAULT '1' COMMENT '会员等级 取字典',
  `skin` varchar(20) DEFAULT NULL COMMENT '用户皮肤',
  `layout` int DEFAULT '1' COMMENT '布局设置1：左侧菜单2：顶部菜单',
  `auto_menu` bit(1) DEFAULT NULL COMMENT '是否自动分割菜单',
  `one_level_menu` bit(1) DEFAULT NULL COMMENT '一级菜单是否隐藏',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人',
  `role_id` bigint DEFAULT NULL COMMENT '角色ID',
  `hospital_role_id` bigint DEFAULT NULL COMMENT '医院角色ID【子系统】',
  `image_url` varchar(300) DEFAULT NULL COMMENT '头像路径',
  `identity_cards_image` varchar(300) DEFAULT NULL COMMENT '身份证照片',
  `user_type` int DEFAULT NULL COMMENT '用户类型:1：医生类用户3：代理商/运营商4：普通用户',
  `ethnic` varchar(24) DEFAULT NULL COMMENT '民族',
  `register_code` varchar(36) DEFAULT NULL COMMENT '注册码',
  `qq_number` varchar(30) DEFAULT NULL COMMENT 'qq账号',
  `wechat` varchar(30) DEFAULT NULL COMMENT '微信号',
  `weibo` varchar(200) DEFAULT NULL COMMENT '微博地址',
  `open_id_qq` varchar(36) DEFAULT NULL COMMENT 'qq注册生成id',
  `miniapp_openid` varchar(50) DEFAULT NULL COMMENT '小程序院openId',
  `open_id_weibo` varchar(36) DEFAULT NULL COMMENT '微博注册生成ID',
  `open_id_wechat` varchar(36) DEFAULT NULL COMMENT '微信的openID',
  `open_push` bit(1) DEFAULT b'1' COMMENT '是否开启极光推送',
  `register_type` int DEFAULT NULL COMMENT '注册渠道，字典定义',
  `enterprise_user_id` varchar(100) DEFAULT NULL COMMENT '企微成员用户ID',
  `union_id` varchar(500) DEFAULT NULL COMMENT 'unionid',
  `dubbing_type` int DEFAULT NULL COMMENT '配音类型',
  `student_name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `S_MOBALE` (`mobile`) USING BTREE,
  KEY `index_name` (`mobile`,`account`,`open_id_wechat`,`miniapp_openid`),
  KEY `userType` (`user_type`,`register_time`,`modify_time`,`account`,`mobile`,`chinese_name`,`role_id`,`status`,`id`) USING BTREE,
  KEY ```email``` (`email`) USING BTREE,
  KEY `enterprise_user_id` (`enterprise_user_id`) USING BTREE,
  FULLTEXT KEY `chinese_name` (`chinese_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='账户信息表';

CREATE TABLE `s_user_role` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `role_id` bigint NOT NULL COMMENT '角色ID',
  `is_hospital` tinyint(1) DEFAULT '2' COMMENT '1:子系统角色，2:主系统角色',
  `create_id` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `role_id` (`role_id`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC COMMENT='用户角色关系表';

CREATE TABLE `s_menu` (
  `id` bigint NOT NULL COMMENT '菜单的主键ID',
  `sort_id` int DEFAULT NULL COMMENT '排序ID',
  `hospital_sort_id` int DEFAULT NULL COMMENT '医院菜单排序ID【子系统】',
  `parent_id` bigint DEFAULT NULL COMMENT '父级ID',
  `name` varchar(64) NOT NULL COMMENT '菜单名称',
  `hospital_alias_name` varchar(64) DEFAULT NULL COMMENT '医院菜单别名【子系统】',
  `url` varchar(255) DEFAULT NULL COMMENT '菜单URL',
  `hospital_parent_id` bigint DEFAULT NULL COMMENT '医院菜单上下级关系【子系统】',
  `hospital_flag` tinyint(1) DEFAULT '2' COMMENT '1 医院菜单 2非医院菜单3:不属于任何【子系统】',
  `is_hospital` tinyint(1) DEFAULT '2' COMMENT '1 医院定制菜单 2平台定制菜单,3不属于任何【子系统】',
  `icon_class` varchar(100) DEFAULT NULL COMMENT '菜单Class属性对应菜单的图标样式',
  `function_type` int DEFAULT '2' COMMENT '功能类型1:系统菜单2：业务菜单',
  `description` varchar(100) DEFAULT NULL COMMENT '备注',
  `create_id` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `system_code` int DEFAULT NULL COMMENT '系统标识（1 院内  2 院外 ）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='菜单表';

CREATE TABLE `s_roles` (
  `id` bigint NOT NULL COMMENT '角色id',
  `name` varchar(64) DEFAULT NULL COMMENT '角色名称',
  `type` int DEFAULT NULL COMMENT '角色类别:字典配置',
  `login_client` varchar(255) DEFAULT NULL COMMENT '登录的客户端',
  `hospital_id` bigint DEFAULT NULL COMMENT '医院ID【子系统】',
  `hospital_admin_flag` tinyint(1) DEFAULT '2' COMMENT '1 -医院管理员【子系统】',
  `description` varchar(500) DEFAULT NULL COMMENT '角色描述',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_id` bigint DEFAULT NULL COMMENT '创建人ID',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人ID',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='角色表';

CREATE TABLE `s_page_role` (
  `id` bigint NOT NULL COMMENT '主键id',
  `menu_Id` bigint DEFAULT NULL COMMENT '菜单id',
  `role_Id` bigint DEFAULT NULL COMMENT '角色id',
  `resource_id` bigint DEFAULT NULL COMMENT '资源主键id',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_id` bigint DEFAULT NULL COMMENT '创建人ID',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人ID',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='角色资源表';

CREATE TABLE `s_menu` (
  `id` bigint NOT NULL COMMENT '菜单的主键ID',
  `sort_id` int DEFAULT NULL COMMENT '排序ID',
  `hospital_sort_id` int DEFAULT NULL COMMENT '医院菜单排序ID【子系统】',
  `parent_id` bigint DEFAULT NULL COMMENT '父级ID',
  `name` varchar(64) NOT NULL COMMENT '菜单名称',
  `hospital_alias_name` varchar(64) DEFAULT NULL COMMENT '医院菜单别名【子系统】',
  `url` varchar(255) DEFAULT NULL COMMENT '菜单URL',
  `hospital_parent_id` bigint DEFAULT NULL COMMENT '医院菜单上下级关系【子系统】',
  `hospital_flag` tinyint(1) DEFAULT '2' COMMENT '1 医院菜单 2非医院菜单3:不属于任何【子系统】',
  `is_hospital` tinyint(1) DEFAULT '2' COMMENT '1 医院定制菜单 2平台定制菜单,3不属于任何【子系统】',
  `icon_class` varchar(100) DEFAULT NULL COMMENT '菜单Class属性对应菜单的图标样式',
  `function_type` int DEFAULT '2' COMMENT '功能类型1:系统菜单2：业务菜单',
  `description` varchar(100) DEFAULT NULL COMMENT '备注',
  `create_id` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `system_code` int DEFAULT NULL COMMENT '系统标识（1 院内  2 院外 ）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='菜单表';

CREATE TABLE `s_resource` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `menu_id` bigint DEFAULT NULL COMMENT '菜单s_menu主键ID',
  `name` varchar(32) DEFAULT NULL COMMENT '名称',
  `code` varchar(100) DEFAULT NULL COMMENT '资源编码',
  `hospital_flag` tinyint(1) DEFAULT '2' COMMENT '1 医院资源 2非医院资源【子系统】',
  `description` varchar(255) DEFAULT NULL COMMENT '资源的描述，',
  `resource_url` varchar(255) DEFAULT NULL COMMENT '资源URL路由',
  `create_id` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `menu_id_index` (`menu_id`,`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='资源表';

CREATE TABLE `s_role_menu` (
  `id` bigint NOT NULL,
  `role_id` bigint DEFAULT NULL COMMENT '角色ID',
  `menu_id` bigint NOT NULL COMMENT '菜单ID',
  `create_id` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='角色菜单表';



CREATE TABLE `s_mobile_verification_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `mobile` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '手机号码',
  `email` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '邮箱',
  `ip_address` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'ip地址',
  `destination` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '归属地',
  `verification` int DEFAULT NULL COMMENT '验证码',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `client_id` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '发送的客户端',
  `type` tinyint DEFAULT NULL COMMENT '类型，1 注册 2 忘记密码 3修改邮箱 4修改手机号码 5 登录',
  `status` tinyint(1) DEFAULT NULL COMMENT '是否有效',
  `create_time` datetime DEFAULT (now()) COMMENT '创建时间',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC COMMENT='验证码日志表';

CREATE TABLE `s_dictionary` (
  `id` bigint NOT NULL COMMENT '自增id',
  `sort_id` int NOT NULL DEFAULT '1' COMMENT '排序id',
  `parent_id` bigint NOT NULL COMMENT '父级id',
  `name` varchar(120) DEFAULT NULL COMMENT '名称',
  `value` varchar(500) NOT NULL COMMENT '属性值',
  `description` varchar(2000) DEFAULT NULL COMMENT '备注',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态 1:启用2：禁用',
  `create_id` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_id` bigint DEFAULT NULL COMMENT '修改人',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `english` json DEFAULT NULL COMMENT '海外多语言字典配置',
  PRIMARY KEY (`id`),
  KEY `parent_id_index` (`parent_id`,`status`,`sort_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPACT COMMENT='系统数据字典表';


CREATE TABLE `s_user_login_log` (
  `id` bigint NOT NULL,
  `login_time` datetime DEFAULT NULL,
  `account` varchar(255) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `user_name` varchar(255) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `grant_type` varchar(255) DEFAULT NULL,
  `operation` varchar(400) DEFAULT NULL,
  `failed_message` varchar(300) DEFAULT NULL,
  `success_flag` tinyint(1) DEFAULT NULL,
  `cluster_success` tinyint(1) DEFAULT NULL,
  `platform` varchar(255) DEFAULT NULL,
  `ip_address` varchar(50) DEFAULT NULL,
  `destination` varchar(255) DEFAULT NULL,
  `device_name` varchar(255) DEFAULT NULL,
  `resolution` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '分辨率',
  `app_version` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'app 版本号',
  `sys_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '操作系统名称',
  `sys_version` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '操作系统版本',
  `device_id` varchar(255) DEFAULT NULL,
  `manufacturer_name` varchar(255) DEFAULT NULL,
  `mac` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'mac地址',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='登录信息表';
